name : mi sengundo robot


on:
    push:
        branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: paso 1
        run: echo "Hola, este es mi segundo robot en GitHub Actions"
      - name: validar secret
        run: echo "El valor del secreto es ${{ secrets.TOKEN }}"     

